defaults: &settings
  version: 2.2.1
  android_store_url: https://play.google.com/store/apps/details?id=com.zazoapp.client
  iphone_store_url: https://itunes.apple.com/us/app/zazo/id922294638?mt=8
  domain_name: zazoapp.com
  site_name: zazoapp
  app_name: Zazo
  admin_email: admin@zazoapp.com
  support_email: support@zazoapp.com
  app_schema: zazo://
  use_s3: false
  allow_authentication_with_token: false
  verification_code_length: 4
  verification_code_lifetime_minutes: 120
  verification_code_sms_countries:
    - us
    - ch
    - cn
    - de
    - dk
    - es
    - fi
    - fr
    - gb
    - hk
    - il
    - it
    - jp
    - nl
    - nz
    - se

development:
  <<: *settings
  allow_authentication_with_token: true

test:
  <<: *settings

playground:
  <<: *settings
  allow_authentication_with_token: true

staging:
  <<: *settings

production:
  <<: *settings
